### ISSUE TITLE
GESIS not working 

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#3015] opened 2024-07-02 17:40 UTC
The endpoint at GESIS seems to not allow for new launches since [1d8b500](https://github.com/jupyterhub/mybinder.org-deploy/commit/1d8b5008e57f774113b78527cb3cef8070d70bc7)

@rgaiacs

**Comment by rgaiacs** [comment] 2024-07-03 06:24
The issue with GESIS server is not caused by [1d8b500](https://github.com/jupyterhub/mybinder.org-deploy/commit/1d8b5008e57f774113b78527cb3cef8070d70bc7).

On June 21, 2024 at 11:40:38 AM GMT+2, we received a change request from this repository. Our continuous integration failed when trying to apply the changes to our stage server.

I started my holidays on June 21, 2024 and didn't noticed that our continuous integration failed on our stage server.

We continue to receive change requests last week to update Prometheus and Grafana. This changes were not merged. The server continue running. 

On July 2, 2024 at 10:23:55 AM GMT+2, we received a change request to update the build image. This change request was not merged because our stage server was not working as expected.

On July 3, 2024 at 8:21:20 AM GMT+2, I manually skipped the use of the stage server and deploy the build image update to the production server.

I can see incoming traffic to our production server.

cc @arnim

**Closed by rgaiacs** 2024-07-03 06:24 UTC
Labels: question
