### ISSUE TITLE
repo2docker handling of none utf-8 encoded files

### ISSUE THREAD

**Issue by YoniChechik** [jupyterhub/mybinder.org-deploy#1125] opened 2019-08-13 21:27 UTC
this is my error (after trying to fix it myself):
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker_t69z433'...
HEAD is now at c112515 utf-8 bugfix
Error
during build: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
``` 

this is my github
https://github.com/YoniChechik/computer_vision_course

what am I doing wrong?

**Comment by betatim** [comment] 2019-08-13 21:36
That is an interesting bug, thanks for reporting it.

We will look into it. My guess is that your `requirements.txt` is not utf-8 encoded which causes the error. The notebooks aren't considered that early in the build stage.

**Comment by betatim** [comment] 2019-08-13 21:38
Output from running repo2docker locally:
```
$ repo2docker https://github.com/YoniChechik/computer_vision_course
Picked Git content provider.
Cloning into '/var/folders/rr/69pl0sh155l1ncw782764xq00000gn/T/repo2dockerkjatc_o3'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 55 (delta 2), reused 40 (delta 0), pack-reused 0
Unpacking objects: 100% (55/55), done.
Traceback (most recent call last):
  File "/Users/thead/miniconda/envs/bhub/bin/repo2docker", line 11, in <module>
    load_entry_point('jupyter-repo2docker', 'console_scripts', 'repo2docker')()
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/__main__.py", line 354, in main
    r2d.start()
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/app.py", line 714, in start
    self.build()
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/app.py", line 668, in build
    self.log.debug(picked_buildpack.render(), extra=dict(phase="building"))
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/buildpacks/base.py", line 519, in render
    for user, script in self.get_assemble_scripts():
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/buildpacks/python/__init__.py", line 124, in get_assemble_scripts
    if not self._should_preassemble_pip:
  File "/Users/thead/git/jupyterhub/repo2docker/repo2docker/buildpacks/python/__init__.py", line 90, in _should_preassemble_pip
    for line in f:
  File "/Users/thead/miniconda/envs/bhub/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

the line that raises the error is opening the `requirements.txt`.

**Comment by MaxNoe** [comment] 2019-08-14 11:53
The encoding before was `utf-16[BOM][dos]` (vim)

in python (with fixing it to utf-8):

```
import chardet

with open('requirements.txt', 'rb') as f:
    requirements = f.read()

result = chardet.detect(requirements)

print('result')

with open('requirements.txt', 'wb') as f:
    f.write(requirements.decode(result['encoding']).encode('utf-8'))
```

**Comment by MaxNoe** [comment] 2019-08-14 11:59
This is how pip deals with different encodings in `requirements.txt`:

https://github.com/pypa/pip/blob/master/src/pip/_internal/utils/encoding.py

In this instance, the `BOM` was the problem, the rest of the file is ascii compatible.

**Comment by betatim** [comment] 2019-08-14 19:31
Thanks a lot for the pointers and investigating! I think we should move this issue to https://github.com/jupyter/repo2docker now that we know where the problem is.

Do you want to make a PR to implement the fix as well? I think having a utility function that implements the pattern you showed of reading some of the file in binary mode and then opening it again with the encoding that `chardet` determined. Or maybe copy the `open` function from pip directly so we get the same behaviour?

**Comment by betatim** [comment] 2019-08-16 05:48
Closed in favour of the new issue in the repo2docker repository.

**Closed by betatim** 2019-08-16 05:48 UTC
