### ISSUE TITLE
error: too many requests to server while pulling image

### ISSUE THREAD

**Issue by AngryMaciek** [jupyterhub/mybinder.org-deploy#2626] opened 2023-05-10 09:02 UTC
### A link to the repository
https://github.com/AngryMaciek/warlock

### Why are you concerned this repository maybe liable for banning?

I am a computational biologist working on mathematical oncology.  
We have developed a tool to run scientific simulations and we used public _mybinder_ service to present the workflow. Everything was fine for long time (a few months ago); I came back to the project, tried to start up the server and encountered the following error:
```
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Successfully pushed gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:bd6c4ac452a97a0882cad0743468e511aa3afbecBuilt image, launching...
Launching server...
Server requested
2023-05-04T10:09:33.050020Z [Normal] Successfully assigned gesis/jupyter-angrymaciek-2dwarlock-2delyf5tee to spko-css-app03
2023-05-04T10:09:33Z [Normal] Container image "jupyterhub/k8s-network-tools:2.0.0" already present on machine
2023-05-04T10:09:33Z [Normal] Created container block-cloud-metadata
2023-05-04T10:09:34Z [Normal] Started container block-cloud-metadata
2023-05-04T10:09:34Z [Normal] Pulling image "gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:bd6c4ac452a97a0882cad0743468e511aa3afbec"
2023-05-04T10:09:38Z [Warning] Failed to pull image "gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:bd6c4ac452a97a0882cad0743468e511aa3afbec": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:bd6c4ac452a97a0882cad0743468e511aa3afbec": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f/manifests/sha256:76fd0b95fd4ccc2fd853585228362675bb7ec9e5e289c3dc0a6c0e39489f5770: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2023-05-04T10:09:38Z [Warning] Error: ErrImagePull
2023-05-04T10:09:38Z [Normal] Back-off pulling image "gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:bd6c4ac452a97a0882cad0743468e511aa3afbec"
2023-05-04T10:09:38Z [Warning] Error: ImagePullBackOff
```

How should I address this problem?

**Comment by rgaiacs** [comment] 2023-05-10 10:11
Hi @AngryMaciek,

https://mybinder.org is a federated network (more at https://mybinder.readthedocs.io/en/latest/about/federation.html). At the moment, you request is being sent to GESIS server. We are GESIS are reconfiguring the servers and one of the issues that we are having is reaching DockerHub rate limit which makes us unable to launch the requested repository.

A work around at the moment is to make your request at https://ovh.mybinder.org/.

We will resolve the DockerHub rate limit in the coming days.

**Comment by uwezi** [comment] 2023-05-10 12:28
What a bad luck for me as well - I was planning to run a student lab with my code on Binder tomorrow. While testing if everything was as fine as it was 3 months ago, I experienced the same problems. But my launch attempts at ovh.mybinder.org seem also to fail.
I am aware that I am using a free platform here - would there be a way I could suggest to our system administrators here at Uppsala University to install our own, local Binder server for the future?

[https://github.com/uwezi/1TE720_content/](https://github.com/uwezi/1TE720_content/)

**Comment by rgaiacs** [comment] 2023-05-10 12:43
@uwezi what is the error that you are having when launch from ovh.mybinder.org?

> would there be a way I could suggest to our system administrators here at Uppsala University to install our own, local Binder server for the future?

Use https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/index.html as your starting point.

**Comment by uwezi** [comment] 2023-05-10 13:03
> @uwezi what is the error that you are having when launch from ovh.mybinder.org?
> 
There are alternating error messages, about just restarting and now the latest
`Found built image, launching...
Too many users on this BinderHub! Try again soon.`

And now it started....

**Comment by uwezi** [comment] 2023-05-11 09:19
Today, right now, it seems impossible to start any Binder session on any of the two hubs 😢

**Comment by AngryMaciek** [comment] 2023-05-29 12:33
Any progress here?

**Comment by rgaiacs** [comment] 2023-05-30 08:39
Hi @AngryMaciek, https://mybinder.org/ is working a lot better now. Can you try and tell us if you encounter the same error? Thanks!

**Comment by AngryMaciek** [comment] 2023-05-30 20:15
After a long container build I now receive the following logs:
```
Step 52/52 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in ea81785d63b4
Removing intermediate container ea81785d63b4
 ---> ed0b408c2cc3
{"aux": {"ID": "sha256:ed0b408c2cc387cadd23ca569cf873c77f151ed2b9a94042154070c9c6cc5932"}}Successfully built ed0b408c2cc3
Successfully tagged gesiscss/binder-r2d-g5b5b759-angrymaciek-2dwarlock-dd4b2f:b76e25e0f11dcfb95595cd74660fa2709dd331e5
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```
And an error afterwards :(

**Comment by AngryMaciek** [comment] 2023-05-31 07:16
I have launched the service once again and this time it started pulling a container which seemingly was already built and after some time my notebook started, I think we are done here :)

**Comment by rgaiacs** [comment] 2023-08-28 08:02
I'm closing this as the issue is old and resolved.

**Closed by rgaiacs** 2023-08-28 08:02 UTC
Labels: question
