### ISSUE TITLE
Javascript in documentation is broken

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2581] opened 2023-04-26 10:31 UTC
Page: https://mybinder-sre.readthedocs.io/en/latest/operation_guide/federation.html

![Screenshot 2023-04-26 at 12-30-32 The mybinder org Federation](https://user-images.githubusercontent.com/1506457/234549098-b1a97d76-7b67-43e6-85c6-3a4504c75276.png)

**Comment by minrk** [comment] 2023-04-26 13:06
That bit is removed in #2569, since it's a duplicate of https://mybinder.readthedocs.io/en/latest/about/status.html#federation-status

**Closed** 2023-04-28 09:08 UTC
