### ISSUE TITLE
Gesis git trigger fails: certificate expired

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#2740] opened 2023-09-14 07:13 UTC
The Gesis git trigger currently fails due to an expired certificate:
https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/6182071584/job/16781184183#step:2:5
```
curl -X POST \
  -F token=${GESIS_TOKEN} \
  -F ref=main \
  https://git.gesis.org/api/v4/projects/ilcm%2Forc2-upgrade-bot/trigger/pipeline
  shell: /usr/bin/bash -e {0}
  env:
    GESIS_TOKEN: ***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
@rgaiacs @arnim

**Comment by rgaiacs** [comment] 2023-09-14 08:20
Thanks @manics for raise the issue. I open a internal ticket with IT Service.

**Comment by rgaiacs** [comment] 2023-09-14 15:45
`git.gesis.org`'s SSL certificate was re-new. Closing as the problem is fixed.

**Closed by rgaiacs** 2023-09-14 15:45 UTC
